const mongoose = require("mongoose");

const EventSchema = new mongoose.Schema({
  name: { type: String, required: true },
  date: { type: String, required: true },
  time: { type: String, required: true },
  maxPeople: { type: Number, required: true },
  category: { type: String, required: true },
  description: { type: String },
  location: { type: String, required: true },
  address: { type: String, required: true },
  number: { type: String, required: true },
  neighborhood: { type: String },
  city: { type: String, required: true },
  state: {
    type: String,
    required: true,
    enum: [
      "AC",
      "AL",
      "AP",
      "AM",
      "BA",
      "CE",
      "DF",
      "ES",
      "GO",
      "MA",
      "MT",
      "MS",
      "MG",
      "PA",
      "PB",
      "PR",
      "PE",
      "PI",
      "RJ",
      "RN",
      "RS",
      "RO",
      "RR",
      "SC",
      "SP",
      "SE",
      "TO",
    ],
  },
  complement: { type: String, default: "" },
  image: { type: String, default: "sem-image.svg" },
  creator: {
    id: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    name: { type: String },
    email: { type: String },
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

module.exports = mongoose.model("Event", EventSchema);
